name: Conatainer Image CI

on:
  push

jobs:
  build_and_publish:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Container Image
        run:
          podman login --username mbesar --password ${{ secrets.MANAGE_PACKAGES }} ghcr.io
          podman manifest create ghcr.io/mmBesar/radicale:latest
          podman build --platform linux/amd64,linux/arm64 --manifest ghcr.io/mmBesar/radicale:latest .
          podman manifest push ghcr.io/mmBesar/radicale:latest