name: Conatainer Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    container:
      image: ghcr.io/mmBesar/radicale:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to container registry
        run: echo "${{ secrets.MANAGE_PACKAGES }}" | podman login -u mbesar --password-stdin ghcr.io

      - name: Build and push multi-architecture image
        run: |
          podman build --format docker --platform linux/amd64,linux/arm64 -t ghcr.io/mmBesar/radicale:latest .
          podman push ghcr.io/mmBesar/radicale:latest